COIN_TYPE_BTC_CNY = "btc_cny"
COIN_TYPE_LTC_CNY = "ltc_cny"
COIN_TYPE_CNY = "cny"
COIN_TYPE_USD = "usd"

# Huobi
HUOBI_COIN_TYPE_BTC = 1
HUOBI_COIN_TYPE_LTC = 2
HUOBI_COIN_TYPE_ETH = "ethcny"
HUOBI_COIN_TYPE_ETC = "etccny"

# okcoin

OKCOIN_COIN_TYPE_BTC = "btc_cny"
OKCOIN_COIN_TYPE_LTC = "btc_ltc"
OKCOIN_COIN_TYPE_ETH = "btc_eth"