COIN_TYPE_BTC_CNY = "btc_cny"
COIN_TYPE_LTC_CNY = "ltc_cny"
HUOBI_COIN_TYPE_BTC = 1
HUOBI_COIN_TYPE_LTC = 2
HUOBI_COIN_TYPE_ETH = "ethcny"
HUOBI_COIN_TYPE_ETC = "etccny"
COIN_TYPE_CNY = "cny"
COIN_TYPE_USD = "usd"